name: Create Release By Tag

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      #生成更新日志
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: simple
          package-name: v${{ github.ref_name }}
          target-branch: ${{ github.ref_name }}
