name: CI Create Release

on:
  push:
    tags:
      - '*'


jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: echo github
      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      - run: echo "GITHUB_CONTEXT"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/f5l5y5/axios-abort/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false